on:
  push:
    branches:
      - main
      - master
      - actions
  pull_request:
    branches:
      - main
      - master

name: Build-test

jobs:
  Build-test:
    runs-on: ubuntu-20.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_HOME: /opt/R/4.1.2/lib/R
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-pandoc@v1
      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: 4.1.2

      - name: Install Linux package dependencies
        run: |
          sudo apt-get install -y build-essential cmake curl git git-core lcov make wget libcairo2-dev libcurl4-openssl-dev libgit2-dev libicu-dev libpng-dev libssl-dev libtbb2 libxml2-dev libxt6 libxt-dev
          sudo apt-get install -y clang clang-tidy

      - name: Install R package dependencies
        continue-on-error: true
        run: |
          install.packages(c("devtools", "Rcpp"))
        shell: Rscript {0}

      - name: Testing R code on R REPL
        continue-on-error: true
        run: |
          devtools::install(".", dependencies = TRUE)
          library(anRcppSample)
          devtools::test()
          print(covr::package_coverage())
          lintr::lint_package()
          devtools::document()
        shell: Rscript {0}

      - name: Install this package
        run: |
          mkdir -p tests/build
          R CMD build .
          R CMD INSTALL anRcppSample_0.0.0.9000.tar.gz

      - name: Testing C++ code in the R package
        continue-on-error: true
        working-directory: ./tests/build
        run: |
          cmake ..
          make
          echo "library(anRcppSample)" | ./test_sample --output-on-failure

      - name: Report coverage of C++ code in the R package
        continue-on-error: true
        working-directory: ./tests/build/CMakeFiles/test_sample.dir
        run: |
          lcov -d . -c -o coverage.info
          lcov -r coverage.info "/usr/*" "*/googletest/*" "/opt/boost*" -o coverageFiltered.info
          genhtml -o lcovHtml --num-spaces 4 -s --legend coverageFiltered.info

      - name: Check C++ code in the R package
        continue-on-error: true
        run: |
          echo "-I $(find /usr -name R.h | head -1 | xargs dirname)" "$(Rscript -e 'cat(paste(paste0(" -I ", .libPaths(), "/Rcpp/include"), sep="", collapse=" "))')" > _r_includes
          clang-tidy src/*.cpp tests/*.cpp -checks=perf\* -- -I src $(cat _r_includes) -I tests/build/googletest-src/googletest/include || echo "Non-zero exit code"
